name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Top Langs SVG
        run: |
          curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=Sm0kyday0&layout=compact&theme=radical&token=${{ secrets.GH_STATS_TOKEN }}"

      - name: Commit SVG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add top-langs.svg
          git commit -m "Update top-langs" || echo "No changes to commit"
          git push
